apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: foodmarket
build:
  artifacts:
    - image: iteam1337/foodmarket
      context: .
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl:
    defaultNamespace: foodmarket
